# test_handle的数据库检查
# 1、检查r_request_order表order_status为FSMROS02（进行中）
# 2、检查r_work_order表order_status为FSMWOS03（进行中）
# 3、根据r_order的request_order_id+work_order_id查询，检查r_order表work_order_state为FSMWOS03，
# 检查request_order_status为FSMROS02，current_stage_code为APPOINT_TIME，order_status（聚合订单状态）为FSMIOS01（进行中）
# 4、根据r_task_order表request、work、task id关联r_task_order,task_status为FSMTOS01（待预约），engineer_id为入参值
sql_check_handle = "SELECT t2.order_status AS request_status,t1.order_status AS work_status,t3.work_order_state,t3.request_order_status,t3.current_stage_code,t3.order_status,t4.task_status,t4.engineer_id FROM rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id  AND t3.request_order_id = t4.request_order_id  AND t3.task_order_id = t4.id WHERE t1.id in   "

# 下单入参查询
place_order = "select t2.rel_key as store_id ,t4.brand_id  from   	rdp_system.r_user t1  LEFT JOIN 	rdp_system.r_user_scope_data t2 on  t1.id=t2.user_id   left join rdp_fsm.r_store_info  t4 on t4.id=t2.rel_key where t1.phone = '18810007982' and  t4.tenant_id='1578547367151484930' LIMIT 0,1"
prace_order_version = "select id,version  from rdp_fsm.r_production t1  where product_name='%s'"
# 根据用户手机号查询用户id和account
user_info = 'SELECT id,real_name,email  FROM rdp_system.r_user WHERE phone='

place_check = "SELECT t1.id,t1.brand_id,t1.tenant_id,t1.order_status ,	t2.current_stage_code,t2.order_status ,t2.request_order_status from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2  on t1.id=t2.request_order_id  WHERE t1.id='%s'"

# 高空作业，规格属性
pro_duction = "SELECT t3.properties from rdp_fsm.r_production_sku_template t3 where  (t3.production_id,t3.version)=(select  t2.production_id,t2.version from  rdp_fsm.r_production t1 LEFT JOIN rdp_fsm.r_production_version t2 on t1.id=t2.production_id  where t1.product_name='%s'"
pro_duction2 = "ORDER BY t2.update_time DESC LIMIT 0,1)  LIMIT 0,1"

# 修改订单查询订单参数
update_order = "SELECT t1.id,t1.create_user,t1.create_time,t1.update_user,t1.update_time,t1.is_delete,t1.tenant_id,t1.brand_id, t1.store_id,t1.request_type,t1.order_status,t1.order_code,t1.submit_deal_status,t1.has_evaluate,t2.expected_start_time,t2.expected_end_time,t2.urgency_degree,t2.service_id,t2.service_version  from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2  on t1.id=t2.request_order_id   WHERE   t1.order_status='FSMROS01' and t2.order_status='FSMIOS01' and t2.request_order_status='FSMROS01'  and   t2.current_stage_code='WAIT_OUTLETS_CONFIRM'   and  (t1.create_user)=(SELECT id from rdp_system.r_user where phone='18810007982')  and (t1.id)=(SELECT t1.id  from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2  on t1.id=t2.request_order_id   WHERE   t1.order_status='FSMROS01' and t2.order_status='FSMIOS01' and t2.request_order_status='FSMROS01'  and   t2.current_stage_code='WAIT_OUTLETS_CONFIRM'   and  (t1.create_user)=(SELECT id from rdp_system.r_user where phone='18810007982')  order by t1.create_time desc LIMIT 0,1)"
# 验证修改订单后的数据
update_check = "SELECT t1.order_status,t2.order_status,t2.request_order_status ,t2.current_stage_code,t3.remark from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2  on t1.id=t2.request_order_id  LEFT JOIN  rdp_fsm.r_request_order_attached t3 on t2.request_order_id =t3.request_order_id WHERE  t1.id='%s'  ORDER BY t3.update_time  DESC LIMIT 0,1"

# 获取用户
get_name = "select t3.real_name from rdp_system.r_user t3 WHERE (t3.id)=(select  t2.create_user from  rdp_fsm.r_production t1 LEFT JOIN rdp_fsm.r_production_version t2 on t1.id=t2.production_id  where t1.product_name='%s'"
get_name2 = "ORDER BY t2.update_time DESC LIMIT 0,1)"

# 高空作业
get_high = "select t3.id,t3.create_user,t3.create_time,t3.update_user,t3.update_time,t3.is_delete,t3.value_id,t3.prop_value,t3.key_id,t3.config_key_id, cast(t3.price as char) as price  from rdp_fsm.r_production t1 LEFT JOIN rdp_fsm.r_production_config_key t2 on t1.id=t2.production_id  LEFT JOIN  rdp_fsm.r_production_config_value t3 on t2.id=t3.config_key_id where  t3.is_delete=0 and t1.product_name='%s'   and t2.config_type='PLATFORM'   and t3.prop_value='是'"

# 查询所有未选择服务商的订单
no_chose_order = "SELECT * from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2  on t1.id=t2.request_order_id   WHERE   t1.order_status='FSMROS01' and t2.order_status='FSMIOS01' and t2.request_order_status='FSMROS01'  and   t2.current_stage_code='WAIT_OUTLETS_CONFIRM'   and  (t1.create_user)=(SELECT id from rdp_system.r_user where phone='18810007982')  order by t1.create_time desc LIMIT 0,1"
# no_chose_order ="SELECT * from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2  on t1.id=t2.request_order_id   WHERE   t2.current_stage_code='WAIT_OUTLETS_CONFIRM'   and  (t1.create_user)=(SELECT id from rdp_system.r_user where phone='18810007982')  order by t1.create_time desc LIMIT 0,1"
# 网点查询
#order_choose = "SELECT t3.id ,t3.supplier_id,t3.outlets_name ,t4.company_name  FROM rdp_system.r_user t1 LEFT JOIN  rdp_fsm.r_supplier_rel_user t2 on t1.id=t2.user_id LEFT JOIN rdp_fsm.r_supplier_outlets t3 ON t2.outlet_id=t3.id  LEFT JOIN  rdp_system.r_company_info t4 on t3.tenant_id=t4.tenant_id   where t1.phone='18810007982' GROUP BY  t3.id"
order_choose ="select t3.id as outletsId,t2.supplier_id,t2.id as sku_id,t1.product_name from  rdp_fsm.r_production t1 LEFT JOIN rdp_fsm.r_production_sku_supplier t2  on t1.id=t2.production_id LEFT JOIN  rdp_fsm.r_supplier_outlets t3 on t2.supplier_id=t3.supplier_id   where t3.outlets_status='FSMSS01' and  t3.tenant_id='1578551911591788546'  and  (t2.template_id)=(SELECT t4.id from rdp_fsm.r_production_sku_template t4 where  (t4.production_id)=(select  t5.id from  rdp_fsm.r_production t5 where t5.product_name='空调维修自动化')  LIMIT 0,1)  and t3.outlets_name='浦口体验店'"

order_check = "select t1.order_status ,t2.work_order_state ,t2.current_stage_code,t2.order_status,t2.request_order_status,t3.order_status from rdp_fsm.r_request_order t1 LEFT JOIN rdp_fsm.r_order t2 on  t1.id=t2.request_order_id LEFT JOIN rdp_fsm.r_work_order t3 on t2.work_order_id= t3.id  where t3.id='%s'"

# 预约时间
time_app = "SELECT t1.task_order_id FROM rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id AND t3.task_order_id = t4.id WHERE t2.order_status = 'FSMROS02' AND t1.order_status = 'FSMWOS03'  AND t3.current_stage_code = 'APPOINT_TIME' AND t3.request_order_status = 'FSMROS02' AND t3.order_status = 'FSMIOS01' AND t4.task_status = 'FSMTOS01' and (t4.engineer_id)=(select id from rdp_system.r_user t5 where t5.phone='18810007982' )"

time_app_check = "SELECT t2.order_status AS request_status,t1.order_status AS work_status,t3.request_order_status,t3.current_stage_code,t3.order_status,t4.task_status FROM rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id  AND t3.request_order_id = t4.request_order_id  AND t3.task_order_id = t4.id  where  t4.id in  %s"
# time_app_check = "SELECT t2.order_status AS request_status,t1.order_status AS work_status,t3.request_order_status,t3.current_stage_code,t3.order_status,t4.task_status,t4.engineer_id,t3.order_code FROM rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id  AND t3.request_order_id = t4.request_order_id  AND t3.task_order_id = t4.id  where t4.engineer_id='1562264614939467777'  and  t4.id='%s'"
# 订单确认的用户
sql_user_id = "SELECT id from rdp_system.r_user where phone ="

# 入参request_order_id：任务单：正常完成，operation_type='FSMTOSOT01'
confirm_requestOrderId01 = "SELECT DISTINCT	t1.id  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id  	LEFT JOIN rdp_fsm.r_order t4 ON t1.id = t4.request_order_id  and t2.id =t4.work_order_id and t3.id =t4.task_order_id WHERE 	t1.order_status = 'FSMROS03'  	AND t2.order_status = 'FSMWOS03'  	AND t3.task_status = 'FSMTOS03'  	AND t3.operation_type='FSMTOSOT01' 	AND t4.current_stage_code='WAIT_CONFIRM' 	AND t1.create_time > '2022-09-01'  	AND t1.tenant_id = '1578547367151484930'  ORDER BY 	t1.create_time DESC "

# 入参request_order_id：任务单：到店未服务,operation_type='FSMTOSOT05'
confirm_requestOrderId02 = "SELECT 	t1.id  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id  	LEFT JOIN rdp_fsm.r_order t4 ON t1.id = t4.request_order_id and t2.id =t4.work_order_id and t3.id =t4.task_order_id  WHERE 	t1.order_status = 'FSMROS03'  	AND t2.order_status = 'FSMWOS03'  	AND t3.task_status = 'FSMTOS03'  	AND t3.operation_type='FSMTOSOT05' 	AND t4.current_stage_code='WAIT_CONFIRM' 	AND t1.create_time > '2022-09-01'  	AND t1.tenant_id = '1578547367151484930'  ORDER BY 	t1.create_time DESC"

# 入参request_order_id：工单：电话指导完成,operation_type='FSMWOSCS01'
confirm_requestOrderId03 = "SELECT DISTINCT 	t1.id  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id AND t2.id = t3.work_order_id 	LEFT JOIN rdp_fsm.r_order t4 ON t1.id = t4.request_order_id and t2.id =t4.work_order_id   WHERE 	t1.order_status = 'FSMROS03'  	AND t2.order_status = 'FSMWOS03'  	AND t2.operation_type='FSMWOSCS01' and t3.task_status='FSMTOS03' 	AND t4.current_stage_code = 'WAIT_CONFIRM'  	AND t1.create_time > '2022-09-01'  	AND t1.tenant_id = '1578547367151484930'  ORDER BY 	t1.create_time DESC"

# 入参request_order_id：工单：误发起完成,operation_type='FSMROS04003'
confirm_requestOrderId04 = "SELECT DISTINCT 	t1.id  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id AND t2.id = t3.work_order_id 	LEFT JOIN rdp_fsm.r_order t4 ON t1.id = t4.request_order_id and t2.id =t4.work_order_id   WHERE 	t1.order_status = 'FSMROS03'  	AND t2.order_status = 'FSMWOS03'  	AND t2.operation_type='FSMROS04003' and t3.task_status='FSMTOS03' 	AND t4.current_stage_code = 'WAIT_CONFIRM'  	AND t1.create_time > '2022-09-01'  	AND t1.tenant_id = '1578547367151484930'  ORDER BY 	t1.create_time DESC"

# 入参request_order_id：工单：协商完成,abnormal_operation_type='ABNOPT03'
confirm_requestOrderId05 = "SELECT DISTINCT 	t1.id  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id  	AND t2.id = t3.work_order_id 	LEFT JOIN rdp_fsm.r_order t4 ON t1.id = t4.request_order_id  	AND t2.id = t4.work_order_id  WHERE 	t1.order_status = 'FSMROS03'  	AND t2.order_status = 'FSMWOS03'  	AND t2.abnormal_operation_type='ABNOPT03' 	AND t3.task_status = 'FSMTOS03'  	AND t4.current_stage_code = 'WAIT_CONFIRM'  	AND t1.create_time > '2022-09-01'  	AND t1.tenant_id = '1578547367151484930'  ORDER BY 	t1.create_time DESC"

# 订单状态确认，分为已签到未签到
sql_check_condition = "SELECT  DISTINCT CASE 		T3.is_sign_in  		WHEN 'Y' THEN 'ACTUAL_QUOTE' 		else '未签到' 		end is_sign_in 	FROM 		rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 		LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id and t2.id=t3.work_order_id 	WHERE 	T3.is_sign_in ='Y' and 	t1.id IN"

# 订单确认检查
sql_check_confirm = "SELECT DISTINCT 	t1.order_status, 	t2.order_status, 	t3.task_status, 	t4.request_order_status, 	t4.work_order_state, 	t4.order_status, 	t4.confirm_state, 	t4.current_stage_code, 	t5.confirm_result, 	t5.remark, 	t5.confirm_user_id, 	t5.confirm_code  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t1.id = t3.request_order_id  	AND t2.id = t3.work_order_id 	LEFT JOIN rdp_fsm.r_order t4 ON t1.id = t4.request_order_id 	LEFT JOIN (	SELECT 	*  	FROM 	rdp_fsm.r_order_confirm  	WHERE 	id IN ( SELECT 	SUBSTRING_INDEX( GROUP_CONCAT( id ORDER BY create_time DESC ), ',', 1 )  	FROM 	rdp_fsm.r_order_confirm	GROUP BY	request_order_id 	)  	) t5 ON t1.id = t5.request_order_id  	AND t4.work_order_id = t5.work_order_id  WHERE t1.id IN"

# 签到
sign = "select t1.id , t3.id AS request_order_id from rdp_fsm.r_task_order t1 LEFT JOIN rdp_fsm.r_order t2 on t1.id=t2.task_order_id  LEFT JOIN rdp_fsm.r_request_order t3 on  t2.request_order_id=t3.id  LEFT JOIN rdp_fsm.r_work_order t4 on t3.id=t4.request_order_id  and t2.work_order_state='FSMWOS03'  where  (t1.engineer_id)=(SELECT id from rdp_system.r_user where phone='18810007982') and t1.task_status='FSMTOS02'  and t1.is_sign_in='N' and t2.current_stage_code='WAIT_SIGN_IN'  AND t1.create_time > '2022-09-01'  ORDER BY  t2.create_time DESC"
# 获取经纬度
long_lat = "select t2.longitude,t2.latitude from rdp_fsm.r_store_info t2 where  (t2.id)=(select t1.store_id  FROM rdp_fsm.r_request_order t1 WHERE t1.id='%s')"
# 查找待签到数据状态
sign_staus = "SELECT t4.is_sign_in,t2.order_status AS request_status,t1.order_status AS work_status,t3.work_order_state,t3.request_order_status,t3.current_stage_code,t3.order_status,t4.task_status FROM rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id  AND t3.request_order_id = t4.request_order_id  AND t3.task_order_id = t4.id  where  t2.id='%s'"
# 获取签到后
restule = "select t1.id,t1.request_order_id  from rdp_fsm.r_task_order t1 LEFT JOIN  rdp_fsm.r_order t2 on t1.id=t2.task_order_id where t1.is_sign_in='Y' and t2.current_stage_code='IN_SERVICE' and t1.task_status='FSMTOS02' and (t1.engineer_id)=(SELECT id from rdp_system.r_user where phone='18810007982') ORDER BY t1.sign_in_time  DESC  LIMIT 0,1"
# 验证正常完成时状态
result_normal = "SELECT t1.order_status AS work_status,t2.order_status AS request_order_status,t3.work_order_state,t3.task_order_state,t3.order_status,t3.request_order_status,t3.current_stage_code,t3.task_operation_type,t4.task_status,t4.operation_type FROM rdp_fsm.r_work_order t1  LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id AND t3.task_order_id = t4.id WHERE  t4.id = '%s'"
# 预约二次完成查询
return_check = "SELECT t1.order_status AS work_status,t2.order_status AS request_order_status,t3.work_order_state,t3.task_order_state,t3.order_status,t3.request_order_status,t3.current_stage_code,t3.task_operation_type,t4.task_status,t4.operation_type FROM rdp_fsm.r_work_order t1  LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id WHERE  (t4.work_order_id )= (SELECT work_order_id from rdp_fsm.r_task_order where id='%s')"
# 转上级主管验证
turn_super = "SELECT t1.order_status AS work_status,t2.order_status AS request_order_status,t3.work_order_state,t3.task_order_state,t3.order_status,t3.request_order_status,t3.current_stage_code,t3.task_operation_type,t4.task_status,t4.operation_type FROM rdp_fsm.r_work_order t1  LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id  WHERE  t4.id='%s'"

# 获取gropid
group_ip = "select t1.id, t1.request_order_id,t1.prop_id,t1.is_delete,t1.prop_value_id,t1.prop_key_type,t1.group_id,t2.name,t1.prop_value from rdp_fsm.r_request_order_prop_value  t1 LEFT JOIN  rdp_fsm.r_production_prop_key t2  on t1.prop_id=t2.id where t1.request_order_id='%s'  "
# 查询所有可申请延迟的单
delayed_fil = "SELECT t1.task_order_id,t1.request_order_id FROM  rdp_fsm.r_work_order t1  LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id  LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id AND t3.task_order_id = t4.id LEFT JOIN rdp_fsm.r_processed_task t5 ON t4.request_order_id = t5.request_order_id WHERE  ( t4.engineer_id )=(SELECT id FROM  rdp_system.r_user t6 WHERE t6.phone = '18810007982')   and  t3.create_time >'2022-09-10'   and t1.order_status='FSMWOS03'  and t2.order_status='FSMROS02' and  t3.work_order_state='FSMWOS03' and t3.request_order_status='FSMROS02'  and t3.order_status='FSMIOS01' and  t3.is_sign_in='N'  and t4.task_type='FSMTT01'  ORDER BY t3.report_time DESC"
# 延迟申请后状态验证
delay_fil_state = "SELECT t1.order_status,t1.operation_type,t2.order_status,t2.operation_status,t3.work_order_state,t3.request_order_status,t3.order_status ,t3.is_sign_in,t4.task_type FROM  rdp_fsm.r_work_order t1  LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id  LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id AND t3.task_order_id = t4.id LEFT JOIN rdp_fsm.r_processed_task t5 ON t4.request_order_id = t5.request_order_id WHERE  ( t4.engineer_id )=(SELECT id FROM  rdp_system.r_user t6 WHERE t6.phone = '18810007982') and t1.request_order_id='%s'"

#查询所有可申请转单的工单
transfer_order="select t1.id as work_order_id from rdp_fsm.r_work_order t1 LEFT JOIN  rdp_fsm.r_order t2 on t1.request_order_id=t2.request_order_id LEFT JOIN  rdp_fsm.r_task_order t3 on t3.request_order_id=t2.request_order_id where t1.order_status='FSMWOS02' and  t1.supplier_id='1578553284442013697'  and t1.has_transfer_order=0 group by t1.id  ORDER BY t1.update_time DESC "
# 验证转单数据状态显示
transfer_result="select  t1.order_status,t1.is_delete,t1.has_transfer_order,t2.request_order_status,t2.current_stage_code from rdp_fsm.r_work_order t1 LEFT JOIN  rdp_fsm.r_order t2 on t1.request_order_id=t2.request_order_id LEFT JOIN  rdp_fsm.r_task_order t3 on t3.request_order_id=t2.request_order_id where t1.id='%s'"
# 门店转单审核
transfer_handle="select  t1.id  as work_order_id ,t2.id as processed_task_id ,t3.id as transferOrderApplyId from rdp_fsm.r_work_order t1 LEFT JOIN  rdp_fsm.r_processed_task t2 on t1.id=t2.work_order_id LEFT JOIN rdp_fsm.r_transfer_order_apply t3 on  t2.request_order_id=t3.request_order_id  where   t1.order_status='FSMWOS02' and t1.supplier_id='1578553284442013697'  and t1.has_transfer_order=1    group by t1.id ORDER BY t1.dead_line DESC"



# 查询所有延迟单审核
delay = "SELECT t1.request_order_id,t5.id AS processedTaskId  FROM rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id  AND t1.request_order_id = t3.request_order_id  LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id AND t3.task_order_id = t4.id  LEFT JOIN rdp_fsm.r_processed_task  t5 on t4.request_order_id=t5.request_order_id WHERE t1.order_status = 'FSMWOS03' AND t1.operation_type='FSMWOSCS04' AND t2.order_status = 'FSMROS03' AND t2.operation_status='FSMROS03002'  AND t3.work_order_state = 'FSMWOS03' AND t3.request_order_status = 'FSMROS03' AND ( t4.engineer_id )=(SELECT id FROM rdp_system.r_user t5 WHERE  t5.phone = '18810007982') AND t3.order_status = 'FSMIOS01' ORDER BY t3.report_time DESC"
# 查询延迟审批后的状态
delay_state = "SELECT t1.order_status,t1.operation_type,t2.order_status,t2.operation_status,t3.work_order_state,t3.request_order_status,t3.order_status FROM  rdp_fsm.r_work_order t1  LEFT JOIN rdp_fsm.r_request_order t2 ON t1.request_order_id = t2.id  LEFT JOIN rdp_fsm.r_order t3 ON t1.id = t3.work_order_id AND t1.request_order_id = t3.request_order_id LEFT JOIN rdp_fsm.r_task_order t4 ON t3.work_order_id = t4.work_order_id AND t3.request_order_id = t4.request_order_id AND t3.task_order_id = t4.id LEFT JOIN rdp_fsm.r_processed_task t5 ON t4.request_order_id = t5.request_order_id WHERE  ( t4.engineer_id )=(SELECT id FROM  rdp_system.r_user t6 WHERE t6.phone = '18810007982') and t1.request_order_id='%s'"

# 获取所有未报价
quote_offer = "SELECT  t1.id AS fee_quote_id,t1.request_order_id,t1.work_order_id, t5.id AS task_order_id  FROM rdp_fsm.r_fee_quote t1 LEFT JOIN rdp_fsm.r_fee_task_summary t2 ON t1.id = t2.quote_id LEFT JOIN rdp_fsm.r_work_order t3 ON t1.work_order_id = t3.id LEFT JOIN rdp_fsm.r_supplier_rel_user t4 ON t3.supplier_id=t4.sup_id  LEFT JOIN  rdp_fsm.r_task_order t5 on t3.request_order_id=t5.request_order_id  where   t1.quote_state='NO_QUOTE'   and   (t4.user_id)=(select id from rdp_system.r_user where phone='18810007982' )  and t1.effect_flag=1  and t4.user_type='engineer'  AND t1.create_time > '2022-09-01'  GROUP BY t1.quote_code"
# 查询所有报价待确认的订单
quote_offer_enter = "SELECT t6.rel_id AS fee_quote_id,t1.request_order_id,t6.id AS processed_task_id FROM rdp_fsm.r_fee_work_summary t1 LEFT JOIN rdp_fsm.r_fee_quote t2 ON t1.quote_id = t2.id  LEFT JOIN rdp_fsm.r_processed_task t6 ON t1.request_order_id = t6.request_order_id WHERE t2.approval_state='APPLY' and t2.quote_state='HAS_QUOTE' and t2.effect_flag =1 "
# 全流程获取待报价确认

quote_process="SELECT t6.rel_id AS fee_quote_id,t1.request_order_id,t6.id AS processed_task_id FROM rdp_fsm.r_fee_work_summary t1 LEFT JOIN rdp_fsm.r_fee_quote t2 ON t1.quote_id = t2.id  LEFT JOIN rdp_fsm.r_processed_task t6 ON t1.request_order_id = t6.request_order_id WHERE t2.approval_state='APPLY' and t2.quote_state='HAS_QUOTE' and t2.effect_flag =1 and t1.request_order_id='%s'"
# 验证数据
quote_check = "select t1.approval_state,t1.approval_remark,t1.quote_state,t1.effect_flag from  rdp_fsm.r_fee_quote  t1 where t1.id='%s'"
# 查询可以取消的订单
cancle_informat = "select t1.request_order_id,t1.order_code from rdp_fsm.r_order t1 LEFT JOIN  rdp_fsm.r_request_order t2 on  t1.request_order_id=t2.id LEFT JOIN  rdp_system.r_user t3 on t1.create_user =t3.id  where t1.is_sign_in='N'   and  t1.create_time >'2022-09-10' and   t2.order_status <> 'FSMROS05' and  t2.order_status  <> 'FSMROS04'  ORDER BY  t1.create_time DESC"

# 可报价的数据
quoteId = "SELECT 	t1.id AS quote_id, 	t4.id AS task_order_id, 	t1.quote_code, 	t1.request_order_id, 	t1.work_order_id, 	T3.supplier_id FROM 	rdp_fsm.r_fee_quote t1 	LEFT JOIN rdp_fsm.r_request_order t2 ON t2.id = t1.request_order_id 	LEFT JOIN rdp_fsm.r_work_order t3 ON t3.id = t1.work_order_id 	LEFT JOIN rdp_fsm.r_task_order t4 ON t4.request_order_id = t2.id 	LEFT JOIN rdp_fsm.r_request_order_tag t5 ON t5.request_order_id = t2.id  	AND t5.id = t4.request_order_tag_id 	LEFT JOIN rdp_fsm.r_sales_item t6 ON t6.request_order_id = t2.id  	AND t6.id = t5.sales_item_id 	LEFT JOIN rdp_fsm.r_production t7 ON t7.id = t6.production_id  WHERE 	t1.effect_flag = '1'  	AND t1.quote_state = 'NO_QUOTE'  	AND t1.is_delete = '0'  	AND T4.is_sign_in = 'Y'  	AND T7.product_name = '空调维修自动化'"

# 根据可报价的数据过滤，查到需要报价的任务单
result_quoteId = "SELECT 	t1.id AS quote_id, 	t4.id AS task_order_id, 	t1.quote_code, 	t1.request_order_id, 	t1.work_order_id, 	T3.supplier_id FROM 	rdp_fsm.r_fee_quote t1 	LEFT JOIN rdp_fsm.r_request_order t2 ON t2.id = t1.request_order_id 	LEFT JOIN rdp_fsm.r_work_order t3 ON t3.id = t1.work_order_id 	LEFT JOIN rdp_fsm.r_task_order t4 ON t4.request_order_id = t2.id 	LEFT JOIN rdp_fsm.r_request_order_tag t5 ON t5.request_order_id = t2.id  	AND t5.id = t4.request_order_tag_id 	LEFT JOIN rdp_fsm.r_sales_item t6 ON t6.request_order_id = t2.id  	AND t6.id = t5.sales_item_id 	LEFT JOIN rdp_fsm.r_production t7 ON t7.id = t6.production_id  WHERE 	t1.effect_flag = '1'  	AND t1.quote_state = 'NO_QUOTE'  	AND t1.is_delete = '0'  	AND T4.is_sign_in = 'Y'  	AND T7.product_name = '空调维修自动化' and t1.id ="

# 报价基础数据校验
sql_check_general = "SELECT 	t7.product_name, 	t7.prof_code, CASE 		 		WHEN HOUR ( t3.sign_in_time ) BETWEEN 20  		AND 24 THEN 			'FSMDNNIGHT' ELSE 'FSMDNDAY'  		END 'dayNight', CASE 		 		WHEN DATE( t3.sign_in_time ) IN ( SELECT holiday_date FROM rdp_fsm.r_national_holiday WHERE is_delete = '0' ) THEN 		'FSMHF02' ELSE 'FSMHF01'  	END 'holidaysFestivals', 	t6.urgency_degree, 	t11.city_level, 	t8.city_id, 	t8.area_id, 	t10.company_id, 	t10.quote_setting, 	t10.settlement_setting  FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t2.request_order_id = t1.id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t3.request_order_id = t1.id 	LEFT JOIN rdp_fsm.r_request_order_tag t4 ON t4.request_order_id = t1.id  	AND t4.id = t3.request_order_tag_id 	LEFT JOIN rdp_fsm.r_sales_item t5 ON t5.id = t4.sales_item_id 	LEFT JOIN rdp_fsm.r_request_order_attached t6 ON t6.id = t4.attached_id 	LEFT JOIN rdp_fsm.r_production t7 ON t7.id = t5.production_id 	LEFT JOIN rdp_fsm.r_store_info t8 ON t8.id = t1.store_id 	LEFT JOIN rdp_system.r_company_info t9 ON t9.tenant_id = t8.tenant_id 	LEFT JOIN rdp_fsm.r_general_config t10 ON t10.company_id = t9.id 	LEFT JOIN rdp_system.r_area t11 ON t8.city_id = t11.id  WHERE 	t3.id ="

# 工时和属性的费用
sql_check_feedetail = "WITH temp1 AS (	SELECT		t1.id AS request_order_id,		t2.id AS work_order_id,		t2.supplier_id,		t3.id AS task_id,		t5.production_id,		t7.prop_id,		t7.prop_value,		t7.prop_value_id,		t7.prop_key_type 	FROM		rdp_fsm.r_request_order t1		LEFT JOIN rdp_fsm.r_work_order t2 ON t2.request_order_id = t1.id		LEFT JOIN rdp_fsm.r_task_order t3 ON t3.request_order_id = t1.id		LEFT JOIN rdp_fsm.r_request_order_tag t4 ON t4.request_order_id = t1.id 		AND t4.id = t3.request_order_tag_id		LEFT JOIN rdp_fsm.r_sales_item t5 ON t5.id = t4.sales_item_id		LEFT JOIN rdp_fsm.r_request_order_attached t6 ON t6.id = t4.attached_id		LEFT JOIN rdp_fsm.r_request_order_prop_value t7 ON t7.group_id = t4.pv_group_id 	),	temp2 AS (	SELECT		t1.id AS product_id,		t1.product_name,		t1.prof_code,		t2.supplier_id,		t4.prop_value,		cast(t4.price as char) as  price,		t4.value_id AS prop_value_id,		t4.key_id 	FROM		rdp_fsm.r_production t1		LEFT JOIN rdp_fsm.r_production_supplier t2 ON t1.id = t2.production_id		LEFT JOIN rdp_fsm.r_production_config_key t3 ON t1.id = t3.production_id 		AND t3.config_type = 'SUPPLIER' 		AND t3.is_delete = '0' 		AND t3.supplier_id = t2.supplier_id		LEFT JOIN rdp_fsm.r_production_config_value t4 ON t4.key_id = t3.key_id 		AND t4.config_key_id = t3.id 	),	temp3 AS (	SELECT		t1.id product_id,		t2.supplier_id,		cast(t5.hours as DECIMAL(10,2)) as hours ,		json_extract( properties, '$[0].value' ) AS prop_value_id 	FROM		rdp_fsm.r_production t1		LEFT JOIN rdp_fsm.r_production_supplier t2 ON t1.id = t2.production_id		LEFT JOIN rdp_fsm.r_production_sku_supplier t5 ON t2.production_id = t5.production_id 		AND t2.supplier_id = t5.supplier_id 		AND t2.version = t5.version 	) SELECT	temp1.prop_key_type,	temp1.prop_value,	temp2.price,	temp3.hours FROM	temp1	LEFT JOIN temp2 ON temp1.supplier_id = temp2.supplier_id 	AND temp1.prop_value_id = temp2.prop_value_id 	AND temp1.production_id = temp2.product_id	LEFT JOIN temp3 ON temp1.supplier_id = temp3.supplier_id 	AND temp1.prop_value_id = temp3.prop_value_id 	AND temp1.production_id = temp3.product_id WHERE	temp1.task_id ="

# 工时单价
sql_check_quoteDetail = "SELECT	* FROM	(	SELECT		t1.supplier_id,		'supplier' AS type,		cast(t1.one_line_price AS CHAR ) AS one_line_price,		cast(t1.new_one_line_price AS CHAR ) AS new_one_line_price,		cast(t1.two_line_price AS CHAR ) AS two_line_price,		cast(t1.three_line_price AS CHAR ) AS three_line_price,		cast(t1.four_line_price AS CHAR ) AS four_line_price,		cast(t1.five_line_price AS CHAR ) AS five_line_price,		t2.day_night,		t2.holidays_festivals,		t2.urgency_degree,		t2.profession_code 	FROM		rdp_fsm.r_profession_supplier t1		LEFT JOIN rdp_fsm.r_profession_template t2 ON t1.template_id = t2.id 	WHERE		t1.is_delete = '0' UNION ALL	SELECT		'',		'platform',		cast(one_line_price  AS CHAR ) AS one_line_price,		cast(new_one_line_price AS CHAR ) AS new_one_line_price,		cast(two_line_price AS CHAR ) AS two_line_price,		cast(three_line_price AS CHAR ) AS three_line_price,		cast(four_line_price AS CHAR ) AS four_line_price,		cast(five_line_price AS CHAR ) AS five_line_price,		day_night,		holidays_festivals,		urgency_degree,		profession_code 	FROM		rdp_fsm.r_profession_template 	) A WHERE	day_night = '%(1)s' 	AND holidays_festivals = '%(2)s' 	AND urgency_degree = '%(3)s' 	AND profession_code = '%(4)s'"

# sql_check_feesummary = "SELECT t11.id AS task_summary_id, t11.task_order_id, cast(t11.artificial_fee as char) as artificial_fee, cast(t11.material_fee  as char) as material_fee, cast(t11.transport_fee  as char) as transport_fee, cast(t11.measures_fee  as char) as measures_fee, cast(t11.additional_fee  as char) as additional_fee FROM 	rdp_fsm.r_fee_quote t1 	LEFT JOIN rdp_fsm.r_request_order t2 ON t2.id = t1.request_order_id 	LEFT JOIN rdp_fsm.r_work_order t3 ON t3.id = t1.work_order_id 	LEFT JOIN rdp_fsm.r_task_order t4 ON t4.request_order_id = t2.id 	LEFT JOIN rdp_fsm.r_fee_task_summary t11 ON t1.id = t11.quote_id 	LEFT JOIN rdp_fsm.r_fee_work_summary t12 ON t1.id = t12.quote_id  WHERE 	t1.effect_flag = '1'  	AND t1.quote_state = 'NO_QUOTE'  	AND t1.is_delete = '0'  	AND t4.id = "

sql_check_feesummary = "SELECT 	t11.id AS task_summary_id, 	t11.task_order_id, 	cast( t11.artificial_fee AS CHAR ) AS artificial_fee, 	cast( t11.material_fee AS CHAR ) AS material_fee, 	cast( t11.transport_fee AS CHAR ) AS transport_fee, 	cast( t11.measures_fee AS CHAR ) AS measures_fee, 	cast( t11.additional_fee AS CHAR ) AS additional_fee  FROM 	rdp_fsm.r_fee_quote t1 	LEFT JOIN rdp_fsm.r_fee_task_summary t11 ON t1.id = t11.quote_id 	LEFT JOIN rdp_fsm.r_fee_work_summary t12 ON t1.id = t12.quote_id  WHERE 	t1.effect_flag = '1'  	AND t1.quote_state = 'NO_QUOTE'  	AND t1.is_delete = '0'  	AND t11.task_order_id = "

cancle_informat = "SELECT t1.id AS request_order_id FROM 	rdp_fsm.r_request_order t1 	LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t3.request_order_id = t1.id  WHERE 	t1.id NOT IN ( 	SELECT DISTINCT 		t1.id AS request_order_id  	FROM 		rdp_fsm.r_request_order t1 		LEFT JOIN rdp_fsm.r_work_order t2 ON t1.id = t2.request_order_id 		LEFT JOIN rdp_fsm.r_task_order t3 ON t3.request_order_id = t1.id  	WHERE 		T3.is_sign_in = 'Y'  		OR t1.operation_status = 'FSMROS03003'  	OR t1.order_status IN ( 'FSMROS04', 'FSMROS05' )) "
# 验证取消订单状态
cancle_state = "select t1.order_status,t1.request_order_status,t1.request_operation_status,t1.task_operation_type,t2.order_status,t2.operation_status from rdp_fsm.r_order t1 LEFT JOIN  rdp_fsm.r_request_order t2 on  t1.request_order_id=t2.id LEFT JOIN  rdp_system.r_user t3 on t1.create_user =t3.id  where t1.is_sign_in='N'   and  t1.create_time >'2022-09-10'  and  t1.request_order_id='%s'"

# 根据worl_order_id 查询用户id
name_work = "select t1.id, t3.user_id from rdp_fsm.r_work_order t1   LEFT JOIN rdp_fsm.r_supplier_outlets t2 on  t1.outlets_id=t2.id left JOIN rdp_system.r_user_scope_data t3 on  t2.id=t3.rel_key  LEFT JOIN  rdp_system.r_user t4 on t3.user_id=t4.id left JOIN  rdp_system.r_user_role t5  on  t4.id=t5.user_id  LEFT JOIN  rdp_system.r_role t6 on t5.role_id=t6.id  where t1.order_status = 'FSMWOS02'  AND t2.is_delete = 0 and  t6.code='engineer'  and t4.phone='18810007982' and t1.id='%s'"
task_order_show = "select  t4.id as task_order_id,t2.id as request_order_id,t3.id as work_order_id   from  rdp_fsm.r_order t1 LEFT JOIN rdp_fsm.r_request_order t2 on t1.request_order_id=t2.id  LEFT JOIN  rdp_fsm.r_work_order t3 on t2.id=t3.request_order_id  LEFT JOIN   rdp_fsm.r_task_order  t4 on t3.id=t4.work_order_id  where t3.id='%s'"
# test_handle的入参
#distribute = "select t1.id as work_order_id,t2.user_id from rdp_fsm.r_work_order t1 LEFT JOIN rdp_fsm.r_supplier_rel_user t2 LEFT JOIN rdp_system.r_user t3 on t2.user_id =t3.id on t1.supplier_id=t2.sup_id and t1.outlets_id = t2.outlet_id where t1.order_status='FSMWOS02'  and t2.user_type='engineer' and t2.is_delete=0 and t3.account ='18810007982' and t1.create_time >'2022-09-10' ORDER BY t1.create_time DESC"
distribute ="select t1.id, t3.user_id from rdp_fsm.r_work_order t1   LEFT JOIN rdp_fsm.r_supplier_outlets t2 on  t1.outlets_id=t2.id left JOIN rdp_system.r_user_scope_data t3 on  t2.id=t3.rel_key  LEFT JOIN  rdp_system.r_user t4 on t3.user_id=t4.id left JOIN  rdp_system.r_user_role t5  on  t4.id=t5.user_id  LEFT JOIN  rdp_system.r_role t6 on t5.role_id=t6.id  where t1.order_status = 'FSMWOS02'  AND t2.is_delete = 0 and  t6.code='engineer' and t4.phone='18810007982' GROUP BY t1.id   ORDER BY  t1.create_time DESC "
# 保存报价后，检查r_fee_detail数据更新是否正确
sql_check_detail = "SELECT 	fee_code, 	fee_name, 	cast( unit_price AS FLOAT ) AS unit_price, 	unit, 	cast( num AS FLOAT ) AS num, cast( total_price AS FLOAT )   total_price, 	remark  FROM 	rdp_fsm.r_fee_detail  WHERE 	is_delete = 0  	AND task_summary_id ="

# 保存后，查看r_fee_task_summary数据正确性
table_task_summary = "select cast(artificial_fee AS FLOAT ) AS artificial_fee,cast(material_fee AS FLOAT ) AS material_fee,cast(transport_fee AS FLOAT ) AS transport_fee,cast(measures_fee AS FLOAT ) AS measures_fee,cast(additional_fee AS FLOAT ) AS additional_fee from rdp_fsm.r_fee_task_summary where id="

# 保存后，sql校验数据正确性
sql_task_summary = "WITH temp1 AS ( 	SELECT 		t3.task_code, 		t2.fee_code, 	CASE 			t2.fee_code  			WHEN 'STANDARD_MATERIAL' THEN 			sum( t2.unit_price * t2.num )  			WHEN 'NON_STANDARD_MATERIAL' THEN 			sum( t2.unit_price * t2.num )  			WHEN 'ARTIFICIAL_FEE' THEN 			sum( t2.unit_price * t2.num )  			WHEN 'TRAFFIC_FEE' THEN 			sum( t2.unit_price * t2.num )  			WHEN 'STAY_FEE' THEN 			sum( t2.unit_price * t2.num )  			WHEN 'TRANSPORT_FEE' THEN 			t2.total_price  			WHEN 'MEASURES_FEE' THEN 			t2.total_price  			WHEN 'ADDITIONAL_FEE' THEN 			sum( t2.total_price ) ELSE ''  		END 'fee', 	t3.complete_time  FROM 	rdp_fsm.r_fee_task_summary t1 	LEFT JOIN rdp_fsm.r_fee_detail t2 ON t1.id = t2.task_summary_id 	LEFT JOIN rdp_fsm.r_task_order t3 ON t1.task_order_id = t3.id  WHERE 	t1.id = '%s'  	AND t2.is_delete = '0'  GROUP BY 	t2.fee_code, 	t3.task_code, 	t3.complete_time  	) SELECT 	task_code, 	type, 	fee  FROM 	( 	SELECT 		task_code, 		complete_time, 		'人工费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'ARTIFICIAL_FEE' )  	GROUP BY 		task_code UNION ALL 	SELECT 		task_code, 		complete_time, 		'材料费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'STANDARD_MATERIAL', 'NON_STANDARD_MATERIAL' )  	GROUP BY 		task_code, 		complete_time UNION ALL 	SELECT 		task_code, 		complete_time, 		'交通费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'TRAFFIC_FEE' )  	GROUP BY 		task_code, 		complete_time UNION ALL 	SELECT 		task_code, 		complete_time, 		'住宿费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'STAY_FEE' )  	GROUP BY 		task_code, 		complete_time UNION ALL 	SELECT 		task_code, 		complete_time, 		'运输费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'TRANSPORT_FEE' )  	GROUP BY 		task_code, 		complete_time UNION ALL 	SELECT 		task_code, 		complete_time, 		'措施费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'MEASURES_FEE' )  	GROUP BY 		task_code, 		complete_time UNION ALL 	SELECT 		task_code, 		complete_time, 		'附加费' AS type, 		sum( fee ) AS fee  	FROM 		temp1  	WHERE 		fee_code IN ( 'ADDITIONAL_FEE' )  	GROUP BY 		task_code, 		complete_time  	) A  ORDER BY 	complete_time"

# 保存后，查看r_fee_work_summary数据正确性
table_work_summary = "SELECT 	cast( artificial_fee AS FLOAT ) AS artificial_fee, 	cast( material_fee AS FLOAT ) AS material_fee, 	cast( transport_fee AS FLOAT ) AS transport_fee, 	cast( measures_fee AS FLOAT ) AS measures_fee, 	cast( additional_fee AS FLOAT ) AS additional_fee, 	cast( tax_fee AS FLOAT ) AS tax_fee, 	cast( total_fee AS FLOAT ) AS total_fee, 	cast( total_with_tax  AS FLOAT ) AS total_with_tax FROM 	rdp_fsm.r_fee_work_summary WHERE 	quote_id="

# 保存后，sql校验r_fee_work_summary正确性,含税
sql_worksummary_withtax = "WITH temp1 AS (  SELECT 	t2.fee_code, CASE 		t2.fee_code 		WHEN 'STANDARD_MATERIAL' THEN 		sum( t2.unit_price * t2.num )  		WHEN 'NON_STANDARD_MATERIAL' THEN 		sum( t2.unit_price * t2.num )  		WHEN  'ARTIFICIAL_FEE' THEN 		sum( t2.unit_price * t2.num )  		WHEN  'TRAFFIC_FEE' THEN 		sum( t2.unit_price * t2.num )  		WHEN  'STAY_FEE' THEN 		sum( t2.unit_price * t2.num )  		WHEN 'TRANSPORT_FEE' THEN 		sum(t2.total_price )  		WHEN  'MEASURES_FEE' THEN 		sum(t2.total_price ) 	  WHEN  'ADDITIONAL_FEE' THEN 		sum(t2.total_price )	ELSE ''  	END 'fee'  FROM rdp_fsm.r_fee_task_summary t1 left join rdp_fsm.r_fee_detail t2  on t1.id=t2.task_summary_id WHERE 	t1.quote_id = '%s' 	AND t2.is_delete = '0'  GROUP BY 	t2.fee_code),    temp2 as(select '应付含税金额' as type, round(sum(fee),2) as fee from temp1 ), 	 	temp3 as(select '税费' as type, round(sum(fee),2) as fee from ( 	select '材料税费' as type, sum(fee)/1.13*0.13 as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all  	select '服务税费' as type, sum(fee)/1.06*0.06 as fee from temp1 where fee_code not in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL'))A) 	 	 	select '材料费' as type, sum(fee) as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all  	select '人工费' as type, sum(fee) as fee from temp1 where fee_code in ('ARTIFICIAL_FEE') 	union all  	select '交通费' as type, sum(fee) as fee from temp1 where fee_code in ('TRAFFIC_FEE') 	union all  	select '住宿费' as type, sum(fee) as fee from temp1 where fee_code in ('STAY_FEE') 	union all  	select '运输费' as type, sum(fee) as fee from temp1 where fee_code in ('TRANSPORT_FEE') 	union all  	select '措施费' as type, sum(fee) as fee from temp1 where fee_code in ('MEASURES_FEE') 	union all  	select '附加费' as type, sum(fee) as fee from temp1 where fee_code in ('ADDITIONAL_FEE') 	union all 	select '材料税费' as type, sum(fee)/1.13*0.13 as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all 	select '服务税费' as type, sum(fee)/1.06*0.06 as fee from temp1 where fee_code not in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all 	select '税费' as type, round(sum(fee),2) as fee from ( 	select '材料税费' as type, sum(fee)/1.13*0.13 as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all  	select '服务税费' as type, sum(fee)/1.06*0.06 as fee from temp1 where fee_code not in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL'))A   union all 	select '应付不含税金额' as type, round(temp2.fee-temp3.fee,2) as fee from temp2,temp3 	union all 	select '应付含税金额' as type, round(sum(fee),2) as fee from temp1"

# 保存后，sql校验r_fee_work_summary正确性,含税
sql_worksummary_withnotax = "WITH temp1 AS (  SELECT 	t2.fee_code, CASE 		t2.fee_code 		WHEN 'STANDARD_MATERIAL' THEN 		sum( t2.unit_price * t2.num )  		WHEN 'NON_STANDARD_MATERIAL' THEN 		sum( t2.unit_price * t2.num )  		WHEN  'ARTIFICIAL_FEE' THEN 		sum( t2.unit_price * t2.num )  		WHEN  'TRAFFIC_FEE' THEN 		sum( t2.unit_price * t2.num )  		WHEN  'STAY_FEE' THEN 		sum( t2.unit_price * t2.num )  		WHEN 'TRANSPORT_FEE' THEN 		sum(t2.total_price )  		WHEN  'MEASURES_FEE' THEN 		sum(t2.total_price ) 	  WHEN  'ADDITIONAL_FEE' THEN 		sum(t2.total_price )	ELSE ''  	END 'fee'  FROM rdp_fsm.r_fee_task_summary t1 left join rdp_fsm.r_fee_detail t2  on t1.id=t2.task_summary_id WHERE 	t1.quote_id = '%s' 	AND t2.is_delete = '0'  GROUP BY 	t2.fee_code)  	select '材料费' as type, sum(fee) as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all  	select '人工费' as type, sum(fee) as fee from temp1 where fee_code in ('ARTIFICIAL_FEE') 	union all  	select '交通费' as type, sum(fee) as fee from temp1 where fee_code in ('TRAFFIC_FEE') 	union all  	select '住宿费' as type, sum(fee) as fee from temp1 where fee_code in ('STAY_FEE') 	union all  	select '运输费' as type, sum(fee) as fee from temp1 where fee_code in ('TRANSPORT_FEE') 	union all  	select '措施费' as type, sum(fee) as fee from temp1 where fee_code in ('MEASURES_FEE') 	union all  	select '附加费' as type, sum(fee) as fee from temp1 where fee_code in ('ADDITIONAL_FEE') 	union all 	select '材料税费' as type, sum(fee)*0.13 as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all 	select '服务税费' as type, sum(fee)*0.06 as fee from temp1 where fee_code not in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all 	select '税费' as type, round(sum(fee),2) as fee from ( 	select '材料税费' as type, sum(fee)*0.13 as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all  	select '服务税费' as type, sum(fee)*0.06 as fee from temp1 where fee_code not in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL'))A 	union all 	select '应付不含税金额' as type, sum(fee) as fee from temp1 	union all 	select '应付含税金额' as type, round(sum(fee),2) as fee from ( 	select '应付不含税金额' as type, sum(fee) as fee from temp1 	union all 	select '材料税费' as type, sum(fee)*0.13 as fee from temp1 where fee_code in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL') 	union all  	select '服务税费' as type, sum(fee)*0.06 as fee from temp1 where fee_code not in ('STANDARD_MATERIAL','NON_STANDARD_MATERIAL'))B "

# 提交接口入参
table_quote_submit = "SELECT id,request_order_id,work_order_id,quote_id FROM 	rdp_fsm.r_fee_work_summary WHERE 	quote_id="

# 提交报价检查
check_quote_submit = "SELECT t2.approval_state,t2.quote_state,t2.effect_flag from rdp_fsm.r_fee_work_summary t1 left join rdp_fsm.r_fee_quote t2 on t1.quote_id=t2.id where t2.id= "