project_name: derfu

env: dev
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 唐洪超

# 域名1
host: http://192.168.11.94:30010
# 域名2，支持多个域名配置
app_host:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知 1：发送
notification_type: 1
# 用于跑测全流程开关，TURE为打开，FALSE为关闭
nomal_report: True

is_run: True

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=32525343525978717b2ada66876770d5d43f96792e1baf162a4aba56bb6be5c8
  secret: SEC9603b9148a7dd0c6c1c56a899f6fe045e24a86c93cf0372aa26cdd22469237e0

# 登录用户
login:
  user_name: 18810007982


mysql_db:
  # 数据库开关
  switch: False
  host: 192.168.11.94
  user: root
  password: '9Kp2FOYfL8qyAZtD'
  port: 30005




